GET_FILENAME_COMPONENT(file_name ${download_url} NAME)
SET(test_case_tar_gz ${test_case_dir}/${file_name})
MESSAGE("test_case_tar_gz=${test_case_tar_gz}")
FILE(DOWNLOAD ${download_url} ${test_case_tar_gz} STATUS status SHOW_PROGRESS)
LIST(GET status 0 status_code)
IF(NOT ${status_code} EQUAL 0)    
    MESSAGE(FATAL_ERROR "Downloading test file failed.\n ${status}\n")
ENDIF(NOT ${status_code} EQUAL 0)    
EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E tar xzf ${test_case_tar_gz}
                WORKING_DIRECTORY ${test_case_dir})
